services:
  node-knex-api:
    image: node-knex-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-knex-api
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: npm run dev
    networks:
      - network_node

  node-knex-mysql:
    image: mysql:latest
    container_name: node-knex-mysql
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - volume_node:/var/lib/mysql
    networks:
      - network_node

volumes:
  volume_node:
    driver: local

networks:
  network_node:
    driver: bridge
